#pragma once

enum class CROPS
{
	PARSNIP_SEED, PARSNIP_GROW0, PARSNIP_GROW1, PARSNIP_GROW2, PARSNIP_GROW3, PARSNIP_GROW4,
	BEAN_SEED = 8, BEAN_GROW0, BEAN_GROW1, BEAN_GROW2, BEAN_GROW3, BEAN_GROW4, BEAN_GROW5, BEAN_GROW6, BEAN_GROW7,
	CAULI_SEED = 16 , CAULI_GROW0, CAULI_GROW1, CAULI_GROW2, CAULI_GROW3, CAULI_GROW4,
	POTATO_SEED = 24, POTATO_GROW0, POTATO_GROW1, POTATO_GROW2, POTATO_GROW3, POTATO_GROW4, POTATO_GROW5,
	KALE_SEED = 40, KALE_GROW0, KALE_GROW1, KALE_GROW2, KALE_GROW3, KALE_GROW4,
	TULIP_SEED = 208, TULIP_GROW0, TULIP_GROW1, TULIP_GROW2, TULIP_GROW3, TULIP_GROW4,
	JAZZ_SEED = 216, JAZZ_GROW0, JAZZ_GROW1, JAZZ_GROW2, JAZZ_GROW3, JAZZ_GROW4,

};