#pragma once

#define CHIP_SIZE 48.f

#define FARM_SIZE_WEIGHT 3840.f
#define FARM_SIZE_HEIGHT 3120.f

#define FARM_CHIP_NUM_X 80
#define FARM_CHIP_NUM_Y 65


#define HOUSE_SIZE_WEIGHT 1280.f
#define HOUSE_SIZE_HEIGHT 720.f

#define MYHOUSE_CHIP_NUM_X 27
#define MYHOUSE_CHIP_NUM_Y 15


#define BUSSTOP_SIZE_WEIGHT 1680.f
#define BUSSTOP_SIZE_HEIGHT 1440.f

#define BUSSTOP_CHIP_NUM_X 35
#define BUSSTOP_CHIP_NUM_Y 30


#define TOWN_SIZE_WEIGHT 5760.f
#define TOWN_SIZE_HEIGHT 5280.f

#define TOWN_CHIP_NUM_X 120
#define TOWN_CHIP_NUM_Y 110


#define FOREST_SIZE_WEIGHT 2400.f
#define FOREST_SIZE_HEIGHT 1920.f

#define FOREST_CHIP_NUM_X 50
#define FOREST_CHIP_NUM_Y 40
