#pragma once



enum PLAYER
{
	RIGHT_INIT,	RIGHT_WALK1,RIGHT_WALK2, RIGHT_WALK3, RIGHT_WALK4, RIGHT_WALK5, NONE01, NONE02, NONE03,

	LEFT_INIT,	LEFT_WALK1, LEFT_WALK2, LEFT_WALK3, LEFT_WALK4, LEFT_WALK5, NONE05, NONE06, NONE07,

	BACK_INIT,	BACK_WALK1, BACK_WALK2, BACK_WALK3, BACK_WALK4, NONE08, NONE09, NONE10, NONE11,

	NO_BACK_INIT, NO_BACK_WALK1, NO_BACK_WALK2, NO_BACK_WALK3, NO_BACK_WALK4, NO_NONE08, NO_NONE09, NO_NONE10, NO_NONE11,

	FRONT_INIT, FRONT_WALK1, FRONT_WALK2, FRONT_WALK3, FRONT_WALK4, NONE12, NONE13, NONE14, NONE15,

	NO_FRONT_INIT, NO_FRONT_WALK1, NO_FRONT_WALK2, NO_FRONT_WALK3, NO_FRONT_WALK4, NONE16, NONE17, NONE18, NONE19,

	//NONE, NONE, NONE, NONE, NONE, NONE,
	//NONE, NONE, NONE, NONE, NONE, NONE,
	//NONE, NONE, NONE, NONE, NONE, NONE,
	//NONE, NONE, NONE, NONE, NONE, NONE,
	//NONE, NONE, NONE, NONE, NONE, NONE,
	//NONE, NONE, NONE, NONE, NONE, NONE,
	//NONE, NONE, NONE, NONE, NONE, NONE,
	//NONE, NONE, NONE, NONE, NONE, NONE,
	//NONE, NONE, NONE, NONE, NONE, NONE,
	//NONE, NONE, NONE, NONE, NONE, NONE,
	//NONE, NONE, NONE, NONE, NONE, NONE,
	//NONE, NONE, NONE, NONE, NONE, NONE,
	//NONE, NONE, NONE, NONE, NONE, NONE,
	//NONE, NONE, NONE, NONE, NONE, NONE,
	//NONE, NONE, NONE, NONE, NONE, NONE,
	//NONE, NONE, NONE, NONE, NONE, NONE,
	//NONE, NONE, NONE, NONE, NONE, NONE,

};