#pragma once

enum PLAYER
{
	FRONT_INIT, FRONT_WALK0, FRONT_WALK1, ADD_NEW_ITEM, BLOCK_OUT0, BLOCK_OUT1, NO_FRONT_INIT, NO_FRONT_WALK0, NO_FRONT_WALK1, NO_ADD_NEW_ITEM, NO_BLOCK_OUT0, NO_BLOCK_OUT1,
	
	RIGHT_INIT, RIGHT_WALK0, RIGHT_WALK1, NONE0, EAT, NONE1, LEFT_INIT, LEFT_WALK0, LEFT_WALK1, LEFT_NONE0, LEFT_EAT, LEFT_NONE1,

	BACK_INIT, WALK_BACK1, WALK_BACK2, NONE2, SLEEP, NONE3, LEFT_BACK_INIT, LEFT_WALK_BACK1, LEFT_WALK_BACK2, LEFT_NONE2, LEFT_SLEEP, LEFT_NONE3,

	RUN_FRONT0, RUN_FRONT1, RUN_RIGNH0, RUN_RIGHT1, RUN_BACK0, RUN_BACK1, NO_RUN_FRONT0, NO_RUN_FRONT1, RUN_LEFT0, RUN_LEFT1, NO_RUN_BACK0, NO_RUN_BACK1,

	//NONE, NONE, NONE, NONE, NONE, NONE,
	//NONE, NONE, NONE, NONE, NONE, NONE,
	//NONE, NONE, NONE, NONE, NONE, NONE,
	//NONE, NONE, NONE, NONE, NONE, NONE,
	//NONE, NONE, NONE, NONE, NONE, NONE,
	//NONE, NONE, NONE, NONE, NONE, NONE,
	//NONE, NONE, NONE, NONE, NONE, NONE,
	//NONE, NONE, NONE, NONE, NONE, NONE,
	//NONE, NONE, NONE, NONE, NONE, NONE,
	//NONE, NONE, NONE, NONE, NONE, NONE,
	//NONE, NONE, NONE, NONE, NONE, NONE,
	//NONE, NONE, NONE, NONE, NONE, NONE,
	//NONE, NONE, NONE, NONE, NONE, NONE,
	//NONE, NONE, NONE, NONE, NONE, NONE,
	//NONE, NONE, NONE, NONE, NONE, NONE,
	//NONE, NONE, NONE, NONE, NONE, NONE,
	//NONE, NONE, NONE, NONE, NONE, NONE,

};