#pragma once
enum class TILE_COLL {
	INIT,
	NOTACT,
	COll,
	RIGHTUP,
	RIGHTDOWN,
	LEFTUP,
	LEFTDOWN,
	FREE,

};


enum class TILE_DIRT {
	BASIC,			LEFT_TOP,		MIDDLE_TOP,		RIGHT_TOP,			BASIC_WET, LEFT_TOP_WET, MIDDLE_TOP_WET, RIGHT_TOP_WET,
	H_LINE_TOP,		LEFT_MIDDLE,	MIDDLE_MIDDLE,	RIGHT_MIDDLE,		H_LINE_TOP_WET, LEFT_MIDDLE_WET, MIDDLE_MIDDLE_WET, RIGHT_MIDDLE_WET,
	H_LINE_MIDDLE,	LEFT_BOTTOM,	MIDDLE_BOTTOM,	RIGHT_BOTTOM,		H_LINE_MIDDLE_WET, LEFT_BOTTOM_WET, MIDDLE_BOTTOM_WET, RIGHT_BOTTOM_WET,
	H_LINE_BOTTOM,	W_LINE_LEFT,	W_LINE_MIDDLE,	W_LINE_RIGHT,		H_LINE_BOTTOM_WET, W_LINE_LEFT_WET, W_LINE_MIDDLE_WET, W_LINE_RIGHT_WET
};