#pragma once
enum class TILE_COLL {
	INIT,
	NOTACT,
	COll,
	RIGHTUP,
	RIGHTDOWN,
	LEFTUP,
	LEFTDOWN,
	FREE,

};

enum class MYHOUSE_TILE {

	BAD_BOTTOM,
	BAD,
	TV,
	HITTER,
	TABLE,
	CHAIR,
	MOVE_FARM = 28,
	BLOCK = 29,

};

enum class BUSSTOP_TILE {

	MOVE_TOWN = 25,
	MOVE_FARM = 28,

};

enum class TOWN_TILE {

	MOVE_BUSSTOP = 26,

};


enum class FOREST_TILE {

	MOVE_FARM = 28,
};

enum class FARM_TILE {

	MAPLE_TREE = 0,
	FINE_TREE,
	OAK_TREE,
	MAHOGANI_TREE,
	SMALL_STONE,
	BIG_STONE,
	SMALL_WOOD1,
	SMAA_WOOD2,
	MIDDLE_WOOD,
	BIG_WOOD,
	WEED1,
	WEED2,
	MY_HOUSE,
	SHOP_FLAG = 22,
	MOVE_SHOP = 23,
	MOVE_FOREST = 24,
	MOVE_TOWN = 25,
	MOVE_BUSSTOP = 26,
	MOVE_HOUSE = 27,
	BLOCK = 29,
};


enum class TILE_DIRT {
	BASIC,			LEFT_TOP,		MIDDLE_TOP,		RIGHT_TOP,			BASIC_WET, LEFT_TOP_WET, MIDDLE_TOP_WET, RIGHT_TOP_WET,
	H_LINE_TOP,		LEFT_MIDDLE,	MIDDLE_MIDDLE,	RIGHT_MIDDLE,		H_LINE_TOP_WET, LEFT_MIDDLE_WET, MIDDLE_MIDDLE_WET, RIGHT_MIDDLE_WET,
	H_LINE_MIDDLE,	LEFT_BOTTOM,	MIDDLE_BOTTOM,	RIGHT_BOTTOM,		H_LINE_MIDDLE_WET, LEFT_BOTTOM_WET, MIDDLE_BOTTOM_WET, RIGHT_BOTTOM_WET,
	H_LINE_BOTTOM,	W_LINE_LEFT,	W_LINE_MIDDLE,	W_LINE_RIGHT,		H_LINE_BOTTOM_WET, W_LINE_LEFT_WET, W_LINE_MIDDLE_WET, W_LINE_RIGHT_WET
};