#pragma once
enum class TOOL {
	HOE_FONT00 = 21, HOE_FRONT01, HOE_RIGHT00, HOE_RIGHT01, HOE_BACK, HOE_IN_INVENTROY, HOE_INIT,
	PICKAXE_FONT00 = 63, PICKAXE_FRONT01, PICKAXE_RIGHT00, PICKAXE_RIGHT01, PICKAXE_BACK, PICKAXE_IN_INVENTROY, PICKAXE_INIT,
	AXE_FONT00 = 105, AXE_FRONT01, AXE_RIGHT00, AXE_RIGHT01, AXE_BACK, AXE_IN_INVENTROY, AXE_INIT,

	
	WATER_FONT00 = 147, WATER_FRONT01, WATER_RIGHT00, WATER_RIGHT01, WATER_BACK, WATER_INIT,


};